[versions]
agp = "8.11.1"
appcompat = "1.7.1"
material = "1.12.0"
androidxJunit = "1.2.1"
espresso = "3.6.1"
junit = "4.13.2"
mpandroidchart = "v3.1.0"
bcrypt = "0.10.2"
securityCrypto = "1.1.0"
kotlin = "1.8.22" # <-- add
securityCryptoVersion = "1.1.0-alpha06"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
junit = { module = "junit:junit", version.ref = "junit" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
security-crypto-v110alpha06 = { module = "androidx.security:security-crypto", version.ref = "securityCryptoVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
